local script1 = coroutine.create(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Part1.lua"))()
end)
local script2 = coroutine.create(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Part2.lua"))()
end)
local script3 = coroutine.create(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Main.lua"))()

end)

coroutine.resume(script1)
task.wait(3)
coroutine.resume(script2)
task.wait(3)
coroutine.resume(script3)
