loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Part1.lua"))()
task.wait(2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Part2.lua"))()
task.wait(2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/UknownUsuario12/ParticleEmitter_InstantEdirtionv1.0/main/Main.lua"))()
